const languagesArray = [
  // { value: "", label: "Default", code: "", nativeName: "" },
  {
    value: "en",
    label: "English",
    code: "en",
    nativeName: "English",
    default: true,
  },
  { value: "es", code: "es", label: "Spanish", nativeName: "Spanish" },
  {
    value: "fr",
    code: "fr",
    label: "French",
    nativeName: "français, langue française",
  },
  {
    value: "et_EE",
    label: "Estonian",
    code: "et_EE",
    nativeName: "Estonian (Estonia)",
  },
  { value: "bs_BA", code: "bs_BA", label: "Bosnian", nativeName: "Bosnian" },
  { value: "hr", code: "hr", label: "Croatian", nativeName: "Croatian" },
  { value: "cs", code: "cs", label: "Czech", nativeName: "Czech" },
  { value: "nl", code: "nl", label: "Dutch", nativeName: "Dutch" },
  {
    value: "fr-ca",
    code: "fr_CA",
    label: "French (Canada)",
    nativeName: "français, langue canada",
  },
  { value: "de", code: "de_DE", label: "German", nativeName: "Germany" },
  //   { value: "hu", code: "hu", label: "Hungarian", nativeName: "Hungarian" },
  //   {
  //     value: "zh_Hans_HK",
  //     code: "zh_Hans_HK",
  //     label: "Hong Kong",
  //     nativeName: "Hong Kong",
  //   },
  //   { value: "it", code: "it", label: "Italian", nativeName: "Italian" },
  //   { value: "lv", code: "lv", label: "Latvian", nativeName: "Latvian" },
  //   { value: "lt", code: "lt", label: "Lithuanian", nativeName: "Lithuanian" },
  //   {
  //     value: "mk_MK",
  //     code: "mk_MK",
  //     label: "Macedonian",
  //     nativeName: "Macedonian",
  //   },
  //   { value: "pl", code: "pl", label: "Polish", nativeName: "Polish" },
  //   { value: "pt", code: "pt", label: "Portuguese", nativeName: "Português" },
  //   {
  //     value: "pt-br",
  //     code: "pt_BR",
  //     label: "Portuguese (Brazil)",
  //     nativeName: "Português (brasil)",
  //   },
  //   { value: "ro", code: "ro", label: "Romanian", nativeName: "Romanian" },
  //   { value: "sr", code: "sr", label: "Serbian", nativeName: "Serbian" },
  //   {
  //     value: "sk",
  //     code: "sk",
  //     label: "Slovak",
  //     nativeName: "Slovak",
  //   },
  //   { value: "sl", code: "sl", label: "Slovenian", nativeName: "Slovenian" },
  //   { value: "sv", code: "sv", label: "Swedish", nativeName: "Swedish" },
];

export { languagesArray };
